import type { Metadata } from "next";
import { Merienda } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";
import { SessionProvider } from "@/providers/SessionProvider";
import { ClerkProvider } from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";

const font = Merienda({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artigen | AI Content Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <NextTopLoader
            color="#10B77F"
            crawlSpeed={200}
            height={4}
            crawl={true}
            easing="ease"
          />
          <ToastProvider />
          <SessionProvider>{children}</SessionProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
