import type { Metadata } from "next";
import { Merienda } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";
import { SessionProvider } from "@/providers/SessionProvider";

const font = Merienda({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artigen | AI Content Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToastProvider />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
